config/routes.rb
RailsApp1::Application.routes.draw do
  resources :pokemons

  root 'static#home'
  get '/about' => 'static#about'

  get '/cat-pictures(/:number_of_cats)' => 'static#cats', as: 'cats'
  

  

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
  validates_presence_of :name, :breed, :tier
  validates_format_of :tier, with: /\A[A-Z]{2}\z/, message: "isn't a correctly formatted tier.  For Ubers use UB", allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all.order(:number)
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pokemon }
      else
        format.html { render action: 'new' }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:number, :name, :breed, :tier, :final_evolution)
    end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home

  end

  def about
    
  end

  def cats 
    @cats = CatAPI.new.get_images(results_per_page: params[:number_of_cats] || 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/static_helper.rb
module StaticHelper
   def full_title(page_title = '')
    base_title = "Cat Pic Generator"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div class="layer">
  <span class="menu">Menu</span>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Cat Pictures', cats_path %></li>
    <li><%= link_to 'Pokemon DB', pokemons_path %>
  </ul>
</div>

</body>
</html>

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.select :breed, options_for_select(['Fire', 'Grass', 'Water', 'Psychic', 'Dark', 'Fighting', 'Fairy', 'Bug', 'Ice', 'Electric', 'Flying', 'Steel', 'Normal', 'Rock', 'Ground', 'Dragon', 'Ghost', 'Poison' ].sort) %>
  </div>
  <div class="field">
    <%= f.label :tier %><br>
    <%= f.text_field :tier %>
  </div>
  <div class="field">
    <%= f.label :final_evolution %><br>
    <%= f.check_box :final_evolution %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<h1>Listing pokemons</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Breed</th>
      <th>Tier</th>
      <th>Final evolution</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.number %></td>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.breed %></td>
        <td><%= pokemon.tier %></td>
        <td><%= pokemon.final_evolution %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @pokemon.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pokemon.breed %>
</p>

<p>
  <strong>Tier:</strong>
  <%= @pokemon.tier %>
</p>

<p>
  <strong>Final evolution:</strong>
  <%= @pokemon.final_evolution %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>